### ISSUE TITLE
UnicodeDecodeError in setup.py

### ISSUE THREAD

**Issue by jminnion** [nottrobin/tweet-counter#1]
Attempted to install with pip and received the below error text, apparently related to line 15 of `setup.py`:

```
(capstone_env) C:\path\to\my\dir>pip install tweet-counter
Collecting tweet-counter
  Downloading tweet-counter-0.1.0.tar.gz (2.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error    
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Justin\AppData\Local\Temp\pip-install-meprycub\tweet-counter_e31cf0e3999449898b8b1e82e003bdd0\setup.py", line 15, in <module>
          long_description=open("README.md").read(),
        File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 775: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Did a bit of googling, [seems like character `0x9d` is an "na" symbol from the extended Windows-1252 character set](https://bytetool.web.app/en/ascii/code/0x9d/)?

Also found [it may be related to the README.md file being rendered as part of long_description in setup.py](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/), but again unsure.

Position 775 of the PyPI version of README.md appears to be the first character of the third "otters":
`print(count_tweet("Otters 👪 otters 𝗼𝘁𝘁𝗲𝗿𝘀 otters otters.com/otters"))`

Probably a Windows-specific issue :-) (saw you're at Canonical)

I appreciate the repo, thanks for sharing!

**Comment by nottrobin** [comment]
Ah yeah that's quite likely, thanks for letting me know. Given how special-character-heavy this script is, I suppose I should expect a certain amount of cross platform encoding issues. I'm afraid it's not gonna be easy for me to debug on Windows. If you have any leads I'm happy to help with making experimental changes.
